# Contoh file netlify.toml

[build]
  command = "# no build command"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
